#!/usr/bin/env bash

echo "Enter directory containing one or many CSV inputs:"
read -r host_path

if [ ! -d "$host_path" ]; then
  echo "$host_path is not a directory"
  exit 1
fi

echo "file(s) to be normalized in $host_path"
find . -name '*.csv'

source docker_manager.sh

kill_local_containers

CONTAINER_PATH=/opt/normalizer/inputs

echo "Running docker container from public docker repo"
docker run --name normalizer --privileged -itd -v $(pwd)/$host_path:$CONTAINER_PATH nishanwij/normalizer:latest

create_container_outputs

echo "Creating normalized output CSVs in: $host_path"
copy_normalized_outputs_to_host
